export const jobs = [
  {
    id: 1,
    company: "Amazone",
    date:"5 days ago",
    title: "Senior UI/UX Designer",
    type: "Part-time",
    level: "Senior-Level",
    salary: "$120/hr",
    location: "Mumbai, India",
    logo: "https://tse1.mm.bing.net/th/id/OIP.dLl9UyA6y1GTydI-npnoygHaHv?pid=Api&P=0&h=180",
  },
  {
    id: 2,
    company: "Google",
    date:"12 hours ago",
    title: "Frontend Developer",
    type: "Full-time",
    level: "Mid-Level",
    salary: "$95/hr",
    location: "Bangalore, India",
    logo: "https://upload.wikimedia.org/wikipedia/commons/2/2f/Google_2015_logo.svg",
  },
  {
    id: 3,
    company: "Microsoft",
    date:"2 weeks ago",
    title: "Product Designer",
    type: "Contract",
    level: "Senior-Level",
    salary: "$110/hr",
    location: "Hyderabad, India",
    logo: "https://upload.wikimedia.org/wikipedia/commons/4/44/Microsoft_logo.svg",
  },
  {
    id: 4,
    company: "Flipkart",
    date:"12 days ago",
    title: "UX Researcher",
    type: "Full-time",
    level: "Mid-Level",
    salary: "$70/hr",
    location: "Delhi, India",
    logo: "https://tse2.mm.bing.net/th/id/OIP.JOg1kr5mqLzQ0YMm6M_hOgHaGL?pid=Api&P=0&h=180",
  },
  {
    id: 5,
    company: "Adobe",
    date:"1 month ago",
    title: "UI Designer",
    type: "Part-time",
    level: "Junior-Level",
    salary: "$60/hr",
    location: "Noida, India",
    logo: "https://tse4.mm.bing.net/th/id/OIP.MPHAVL52hadir7pe0HszoAHaEK?pid=Api&P=0&h=180",
  },
  {
    id: 6,
    company: "Netflix",
    date:"13 days ago",
    title: "Product UX Designer",
    type: "Full-time",
    level: "Senior-Level",
    salary: "$130/hr",
    location: "Remote, India",
    logo: "https://tse3.mm.bing.net/th/id/OIP.JFmuUQbJLlVGrlMmamLZHgHaHa?pid=Api&P=0&h=180",
  },
  {
    id: 7,
    company: "Meta",
    date:"2 days ago",
    title: "Interaction Designer",
    type: "Contract",
    level: "Senior-Level",
    salary: "$115/hr",
    location: "Gurgaon, India",
    logo: "https://tse3.mm.bing.net/th/id/OIP.0Y8Hmr7KiAI_InrwDPpj9wHaHI?pid=Api&P=0&h=180",
  },
  {
    id: 8,
    company: "Zomato",
    date:"5 weeks ago",
    title: "UX Designer",
    type: "Full-time",
    level: "Mid-Level",
    salary: "$65/hr",
    location: "Gurgaon, India",
    logo: "https://upload.wikimedia.org/wikipedia/commons/7/75/Zomato_logo.png",
  },
];